version: "3.8"

networks:
  boilerplate-network:

volumes:
  boilerplate-data:
    name: boilerplate-data 

services:
  boilerplate-mongodb:
    container_name: boilerplate-mongodb
    image: mongo:4.2
    restart: always
    command: mongod --quiet --logpath /dev/null 
    ports:
      - 4001:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=123
      - MONGO_INITDB_DATABASE=boilerplate
    networks:
      - boilerplate-network
    volumes:
      - boilerplate-data:/data/db

  boilerplate-api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: boilerplate-api
    ports:
      - 4000:4000
      - 2345:2345
    environment:
      - MONGO_DB_NAME=boilerplate
      - MONGO_DB_USER=user
      - MONGO_PWD=123
      - MONGO_PORT=27017
      - MONGO_HOST=boilerplate-mongodb
    volumes:
     - .:/app:rw,delegated
    networks:
      - boilerplate-network
    depends_on:
      - boilerplate-mongodb